# Generated by Django 5.2.3 on 2025-06-18 05:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='Public identifier')),
                ('artist_uid', models.CharField(blank=True, max_length=256, null=True, verbose_name='Artist UID')),
                ('name', models.CharField(max_length=100)),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('created_by', models.PositiveIntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('country', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('pin_code', models.CharField(max_length=10)),
                ('contact_person_full_name', models.CharField(max_length=100)),
                ('contact_person_phone_1', models.CharField(max_length=15)),
                ('contact_person_phone_2', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_person_email', models.EmailField(max_length=254)),
                ('additional_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='Public identifier')),
                ('event_uid', models.CharField(blank=True, max_length=256, null=True, verbose_name='Event UID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_thumbnails/')),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration_min', models.DurationField(help_text='Minimum duration')),
                ('duration_max', models.DurationField(blank=True, help_text='max duration', null=True)),
                ('created_by', models.PositiveIntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('crew', models.ManyToManyField(blank=True, related_name='event_crews', to='book_now.artist')),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_events', to='book_now.artist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='Public identifier')),
                ('booking_uid', models.CharField(blank=True, max_length=256, null=True, verbose_name='Booking UID')),
                ('user_id', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('estimate_inr', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_artist', to='book_now.artist')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_event', to='book_now.event')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_location', to='book_now.location')),
                ('occations', models.ManyToManyField(blank=True, related_name='booking_occations', to='book_now.occasion', verbose_name='Occasions')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
