# Generated by Django 5.2.3 on 2025-06-18 09:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_now', '0002_alter_artist_profile_picture_achievements_education_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='Public identifier')),
                ('tour_uid', models.CharField(blank=True, max_length=256, null=True, verbose_name='Tour UID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tour_thumbnails/')),
                ('description', models.TextField()),
                ('duration_min', models.DurationField(help_text='Minimum duration')),
                ('duration_max', models.DurationField(blank=True, help_text='max duration', null=True)),
                ('created_by', models.PositiveIntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('crew', models.ManyToManyField(blank=True, related_name='tour_crews', to='book_now.artist')),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_tours', to='book_now.artist')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
