# Generated by Django 5.2.3 on 2025-06-18 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_now', '0003_tours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tours',
            options={'verbose_name': 'Tour', 'verbose_name_plural': 'Tours'},
        ),
    ]
